name: Setup env
description: Setting up environment
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-node@v3
    with:
      node-version: 18
  - name: Install dependencies
    shell: bash
    run: npm ci